import 'server-only';
import { createServerEnv } from '@/lib/env/schema';

export const serverEnv = createServerEnv({
  APP_ENVIRONMENT: process.env.APP_ENVIRONMENT,
  APP_DEFAULT_LOCALE: process.env.APP_DEFAULT_LOCALE,
  APP_DEFAULT_TIMEZONE: process.env.APP_DEFAULT_TIMEZONE,
  PRODUCTION_APP_URL: process.env.PRODUCTION_APP_URL,
  FEATURE_ANALYTICS: process.env.FEATURE_ANALYTICS,
  FEATURE_PREMIUM: process.env.FEATURE_PREMIUM,
  FEATURE_WEB_PUSH: process.env.FEATURE_WEB_PUSH,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  NEXT_PUBLIC_ANALYTICS_KEY: process.env.NEXT_PUBLIC_ANALYTICS_KEY,
  NEXT_PUBLIC_ANALYTICS_HOST: process.env.NEXT_PUBLIC_ANALYTICS_HOST,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  PAYMENT_PROVIDER_SECRET_KEY: process.env.PAYMENT_PROVIDER_SECRET_KEY,
  PAYMENT_WEBHOOK_SECRET: process.env.PAYMENT_WEBHOOK_SECRET,
  EMAIL_PROVIDER_API_KEY: process.env.EMAIL_PROVIDER_API_KEY,
  WEB_PUSH_VAPID_PRIVATE_KEY: process.env.WEB_PUSH_VAPID_PRIVATE_KEY,
  WEB_PUSH_VAPID_SUBJECT: process.env.WEB_PUSH_VAPID_SUBJECT,
  SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
  CRON_SHARED_SECRET: process.env.CRON_SHARED_SECRET,
  DATA_EXPORT_SIGNING_SECRET: process.env.DATA_EXPORT_SIGNING_SECRET,
});
